<a href="https://colab.research.google.com/github/BhaskarKapri07/Learning-PyTorch/blob/main/Pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np

In [ ]:
torch.__version__

'2.3.0+cu121'

### Introduction to Tensors

In [ ]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
# Get the dimensions of the tensor
scaler.ndim

0

In [ ]:
# Get the tensor back as Python int
scaler.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[1,2,3],
                       [2,3,4],
                       [4,5,6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([3, 3])

In [ ]:
MATRIX[0]

tensor([1, 2, 3])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [5,6,7]],
                       [[1,2,3],
                        [3,4,5],
                        [5,6,7]
                       ]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]],

        [[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0,1]

tensor([3, 4, 5])

In [ ]:
TENSOR[1]

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

### Random Tensors
Why Random Tensors?


Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [ ]:
# Create a random tensor of shape (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3566, 0.6400, 0.2710, 0.0554],
        [0.7256, 0.7844, 0.6161, 0.9950],
        [0.2773, 0.9582, 0.9517, 0.7427]])

In [ ]:
# zeros and ones
zero_tensor = torch.zeros(size=(3,3))
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones_tensor = torch.ones(size=(3,3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
### Creating a range of tensors and tensor-like
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
### Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note**: Tensor datatypes is one of the 3 big errors you'll run into with Pytorch and Deep Learning

1. Tensors not right datatype.
2. Tensors not right shape.
3. Tensors not on right device. (cpu, gpu, cuda)

In [ ]:
### Tensor DataTypes
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,   # what datatype is the tensor
                               device=None,  # what device your tensor is on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors


1. Tensors not right datatype - to get datatype, use `tensor.dtype`
2. Tensors not right shape - to get shape, use `tensor.shape`
3. Tensors not on right device. (cpu, gpu, cuda) - to get device, use `tensor.device`

In [ ]:
# create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5852, 0.8602, 0.5398, 0.2678],
        [0.1080, 0.5402, 0.8308, 0.8144],
        [0.3234, 0.1947, 0.7873, 0.1417]])

In [ ]:
# finding details about tensor
print(f'datatype of tensor : {some_tensor.dtype}')
print(f'datatype of shape : {some_tensor.shape}')
print(f'datatype of device : {some_tensor.device}')


datatype of tensor : torch.float32
datatype of shape : torch.Size([3, 4])
datatype of device : cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
1. Addition
2. Subratction
3. Multiplication (element wise)
4. Division
5. Matrix Multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor ([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [ ]:
# Subtract
tensor - 10

tensor([-9, -8, -7])

### Matrix Multiplication

Two main ways of performing multiplication in neural network and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two rules that performing matrix multiplication needs to satisfy:
1. The *inner dimensions* must match
* `(3,2)` @ `(3,2)` won't work
* `(3,2)` @ `(2,3)` will work
2. The resulting matrix has the shape of *outer dimensions*
* `(3,2)` @ `(2,3)` will result in `(3,3)`

In [ ]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value= 0
for i in range(len(tensor)):
  value += tensor [i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.75 ms, sys: 0 ns, total: 1.75 ms
Wall time: 2.36 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 35 µs, sys: 3 µs, total: 38 µs
Wall time: 41.2 µs


tensor(14)

### One of the most common errors in  deep learning: shape error

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

#### To fix out tensor shape issue, we can manipulate shape of one of our tensors using a transpose.

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
x = torch.arange(1,100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max


In [ ]:
# Find the position in the tensor that has the minimum value with argmin() -> returns index postion of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [ ]:
# Find the position in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing

* Reshaping - Reshapes an input tensor to a defined shape
* View - Returns a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way.

In [ ]:
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack functions on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
vstacked = torch.vstack([x,x,x])
vstacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
hstacked = torch.hstack([x,x,x])
hstacked, hstacked.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([27]))

In [ ]:
# torch.squeeze() - removes all single dimension from a target tensor
x_reshaped , x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
squuezed = x_reshaped.squeeze()

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
squuezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
unsqueezed = squuezed.unsqueeze(dim=0)
unsqueezed



tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size = (224,224,3))
print(f'x_original.shape : {x_original.shape}')

# permute the original tensor to rearrange the axis (or dim) order
x_permute = x_original.permute(2,0,1)
print(f'x_permute.shape : {x_permute.shape}')

x_original.shape : torch.Size([224, 224, 3])
x_permute.shape : torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 0.111

In [ ]:
x_permute

tensor([[[0.1110, 0.2415, 0.0463,  ..., 0.5336, 0.5661, 0.5775],
         [0.4853, 0.8598, 0.9012,  ..., 0.8819, 0.6335, 0.4466],
         [0.1005, 0.3483, 0.0508,  ..., 0.1745, 0.0356, 0.9145],
         ...,
         [0.4072, 0.5125, 0.8655,  ..., 0.7414, 0.8827, 0.9545],
         [0.9918, 0.9811, 0.7577,  ..., 0.4609, 0.5889, 0.2666],
         [0.6604, 0.3656, 0.1596,  ..., 0.6870, 0.5062, 0.1344]],

        [[0.6097, 0.6946, 0.8474,  ..., 0.2656, 0.8421, 0.1288],
         [0.5651, 0.1340, 0.2133,  ..., 0.5175, 0.4504, 0.7823],
         [0.5037, 0.2942, 0.3497,  ..., 0.2469, 0.6573, 0.3307],
         ...,
         [0.3060, 0.9665, 0.8168,  ..., 0.8605, 0.2827, 0.2671],
         [0.9056, 0.1654, 0.0256,  ..., 0.5203, 0.9586, 0.4064],
         [0.9940, 0.2171, 0.1721,  ..., 0.8387, 0.0183, 0.1974]],

        [[0.2687, 0.3383, 0.9826,  ..., 0.6718, 0.4933, 0.0555],
         [0.2964, 0.1058, 0.7573,  ..., 0.4474, 0.1703, 0.7493],
         [0.4391, 0.0553, 0.6476,  ..., 0.9220, 0.2971, 0.

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all value of the 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
y = torch.arange(1,28).reshape(3,3,3)
y

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [ ]:
y[0,:,2]

tensor([3, 6, 9])

### PyTorch and NumPy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
*PyTorch tensor to NumPy -> `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch refects numpy's defauly dtype of float64 unless specified otherwise

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# change the value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor, what happens to numpy tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take the random out of random)

In short how a neural network works learns:


`start with random number -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...`


To reduce the randomness in neural networks and pytorch there comes a concept of **random seed**.

Essentialy what the random seed does is "flavour" the randomness.

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.6273, 0.8159, 0.1972, 0.7226],
        [0.9148, 0.2715, 0.5148, 0.7273],
        [0.9844, 0.2922, 0.9524, 0.9343]])
tensor([[0.9173, 0.3850, 0.7482, 0.8792],
        [0.9500, 0.0225, 0.8976, 0.3371],
        [0.3479, 0.0452, 0.1311, 0.7655]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# random but reproducible tensors

# set random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPU = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

#### Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your Own GPU - takes a little bit of setup
3. Use cloud computing - GCP, AWS, Azure

In [ ]:
!nvidia-smi

Mon Jun 10 13:07:02 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   71C    P0              29W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

#### Check for GPU access with PyTorch


In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the number of GPUs
torch.cuda.device_count()

1

#### Putting tensors (and models) on the GPU

The reason we want out tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
# Create a tensor

tensor = torch.tensor([1,2,3], )


# Tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU, if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

#### Moving tensor back to CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy

tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])